# Generated by Django 3.2.22 on 2023-10-31 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emploees',
            new_name='Employees',
        ),
    ]
